model: Phi-3.6-mini-instruct
model_path: model
save_dir: mount/save_dir
finetune_dataset: mount/<run_id>/dataset
max_input_size: <max_input_size>
init_prompt: "<init_prompt>"
number_of_virtual_tokens: <number_of_virtual_tokens>
learning_rate: !!float <learning_rate>
early_stopping_patience: <early_stopping_patience>
epochs: <training_args_epochs>
evaluation_strategy: <evaluation_strategy>
eval_steps: <eval_steps>
save_steps: <save_steps>
seed: <training_args_seed>
finetune_train_nsamples: <finetune_train_nsamples>
finetune_test_nsamples: <finetune_test_nsamples>
finetune_train_batch_size: <finetune_train_batch_size>
finetune_test_batch_size: <finetune_test_batch_size>
